logging:
  level:
    org:
      springframework: 
        security: DEBUG

server:
  servlet:
    session:
      cookie:
        secure: false
      timeout: 300m
      
  ssl:
    key-store: classpath:192_168_0_14_new.p12
    #key-store: classpath:localhost_new.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: 192.168.0.14 certificate
    #key-alias: localhost certificate
    key-password: password
    enabled: false
  #port: 8443
  address: 192.168.0.14
  port: 8080
             
spring:
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB 
    
